export const Questions = [
    {
      prompt: "What is 1 + 3?",
      optionA: "24",
      optionB: "9",
      optionC: "4",
      optionD: "2",
      answer: "C",
    },
    {
      prompt: "Who painted the Mona Lisa?",
      optionA: "Pablo Picasso",
      optionB: "Vincent van Gogh",
      optionC: "Leonardo da Vinci",
      optionD: "Michelangelo",
      answer: "C",
    },
    {
      prompt: "What is the largest planet in our solar system?",
      optionA: "Venus",
      optionB: "Jupiter",
      optionC: "Saturn",
      optionD: "Mars",
      answer: "B",
    },
    {
      prompt: "What is the chemical symbol for gold?",
      optionA: "Ag",
      optionB: "Au",
      optionC: "Fe",
      optionD: "Hg",
      answer: "B",
    },
    {
      prompt: "Who wrote the novel 'Pride and Prejudice'?",
      optionA: "Jane Austen",
      optionB: "Charlotte Brontë",
      optionC: "Emily Dickinson",
      optionD: "Virginia Woolf",
      answer: "A",
    },
    {
      prompt: "What is the capital of France?",
      optionA: "Paris",
      optionB: "London",
      optionC: "Berlin",
      optionD: "Madrid",
      answer: "A",
    },
  ];
  